DROP TABLE IF EXISTS user_otps;
CREATE TABLE user_otps (id INT AUTO_INCREMENT PRIMARY KEY, identifier VARCHAR(255) NOT NULL, otp_type VARCHAR(50) NOT NULL, otp_code VARCHAR(10) NOT NULL, channel VARCHAR(20) DEFAULT 'email', used TINYINT(1) DEFAULT 0, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_identifier_type (identifier, otp_type)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS home_categories (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT, name VARCHAR(100) NOT NULL, icon VARCHAR(100), sort_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_work_experience (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, job_title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, location VARCHAR(255), start_month TINYINT, start_year SMALLINT, end_month TINYINT, end_year SMALLINT, is_current TINYINT(1) NOT NULL DEFAULT 0, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_id (user_id)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_permissions (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL UNIQUE, permissions TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
